### ISSUE TITLE
Add support for all vendors

### ISSUE THREAD

**Issue by desandro** [desandro/3dtransforms#1]
3D transforms are [expected to be supported by Firefox, IE, and Opera in the near future](http://caniuse.com/transforms3d).  Right now the demos and docs are only for `-webkit-transform`.  Other vendor prefixed props should be added, and JS needs to be updated as well.  Docs should be updated to talk about wider support.

**Comment by desandro** [comment]
Left to do:
- [IE 10 should be supporting 3D transforms](http://caniuse.com/#search=3d transforms), so all these demos need to be verified
- add animation keyframes for IE, Opera, and un-prefixed

**Comment by dotnetCarpenter** [comment]
Support for Opera could be to just add a -o- prefix. Would be nice ;-)

**Comment by codeofsumit** [comment]
cube doesn't work in IE10
