### ISSUE TITLE
Hello, I use bootstrap when I wanted to refer to the file, but it does not achieve Responsive web design, Is there a way to achieve automatic scaling this stuff does not destroy the original animated it? I saw inside the parameters of absolute size px, I want it to become relative size, if you look at this idea feasible it?

### ISSUE THREAD

**Issue by tel8618217223380** [desandro/3dtransforms#18]
Hello, I use bootstrap when I wanted to refer to the file, but it does not achieve Responsive web design, Is there a way to achieve automatic scaling this stuff does not destroy the original animated it? I saw inside the parameters of absolute size px, I want it to become relative size, if you look at this idea feasible it?

**Comment by desandro** [comment]
Sorry, but I don't think I'll be able to help with this request.
