### ISSUE TITLE
transform-origin and Safari

### ISSUE THREAD

**Issue by joelbloch** [desandro/3dtransforms#22]
Hello,
I am trying to use your code. The only exception is, the front face is at level 0, and the back-face is at level (-cubeWidth)px.
In order for it to work, the transform-origin must be put to center center -cubeWidth / 2.
However, it seems that management of perspective is totally screwed (in all senses of the term) when transform-origin is changed, under Safari. I created an entry on stackoverflow : http://stackoverflow.com/questions/43536900/transform-origin-and-perspective-with-safari

It is not a problem on your code stricto sensu, but do you have any idea how to solve this problem, as you are the expert in css 3D transforms?

Best Regards,
Joel

**Comment by ghost** [comment]
Love the demo on Safari for Sierra 10.12.3. Could not help noticing that an external CSS loads a lot of junk in [Cube 2](https://desandro.github.io/3dtransforms/examples/cube-02-show-sides.html). Specifically, a file named style.css, which pastes stuff into our local page, like useless button controls. It would be nice if the author had the where-with-all to sit down and intelligently assemble this as a standalone demonstration, or remove from public view. Backboard support demo works. What makes it work is not linked in, downloadable, or useful in any way out here in the real world. Screwing around with node js or bootstrap could be your problem. Second thoughts on MIT computing, eh. Definitely not W3Schools, definitely not clean code. Not working. Sorry.
Sad regards,
Mark

**Comment by joelbloch** [comment]
And yet Mark, I managed to do 99% of a website thanks to the code presented in this page.  I would not brag too loud that nothing works on your end with such emphasis, some would question your own IQ ;)

**Comment by ghost** [comment]
Joel, you are obviously forging ahead with this and all loaded with the essentials to code The Colony's jingo under-verse run by hackers from China. Just imagined MIT somehow had a grip on reality. Still do hope. Your baiting is not intelligent. My comment is a clear signal that someone is tagging MIT on their work, and likely damaging a good name. Which goes with your bait effort. Got to do what you've got to do. FYI the Russian hacker elite are here, compliments of Brexit (no doubt), trying to clean up the NSA mess that perhaps necessitates such sloppy code as fills the Region 3 (3rd world) 'educated' web. No hard feelings. Steep and deep. Good luck crossing the line. Rest assured, your code is unintelligible outside of your insecure network. Which may patch you through to reality occasionally, so you too can talk to yourself. With pretty pictures even. Wow. Jerk off, we call it in all my alma maters.

**Comment by joelbloch** [comment]
Good luck. I am pretty sure you could improve it (your luck) if you take the pink pills the doctors prescribed... :D

**Comment by desandro** [comment]
To your original question: sorry I do not know of a solution.

---

I'm locking this issue.
