### ISSUE TITLE
Increase or decrease carousel item

### ISSUE THREAD

**Issue by anisur3036** [desandro/3dtransforms#25]
How will i increase or decrease carousel item without browser refresh?

**Comment by desandro** [comment]
[In the demo,](https://codepen.io/desandro/pen/wjeBpp) you can change `value="9"` of the `.cells-range` slider.

``` html
<input class="cells-range" type="range" min="3" max="15" value="9" />
```

This sets `cellsCount` in the JavaScript.

**Comment by anisur3036** [comment]
Wow! I got it. Thank you so much.
