### ISSUE TITLE
js/rotate-box.js

### ISSUE THREAD

**Issue by ChaseBoland** [desandro/3dtransforms#26]
Hello Desandro, 

Much appreciation for your work. I was building my spouse an interactive web page using your unique rotating cube design. But I noticed after a recent update file "https://desandro.github.io/3dtransforms/js/rotate-box.js" no longer exists. I cannot discover the solution to remedy my project even when referencing the repository. Here is an example https://codepen.io/ChaseBoland/pen/odjaxB 

Thank you for the support

**Comment by desandro** [comment]
See [Box article](https://3dtransforms.desandro.com/box) and [rotate box demo on CodePen](https://codepen.io/desandro/pen/MGpMOV). Looks like this link wasn't correct in the article. I've changed it.
