### ISSUE TITLE
Replace with Images

### ISSUE THREAD

**Issue by jakedurell** [desandro/3dtransforms#28]
Hello,

The code works fine. I was trying replace the divs with images, as shown below. As a result, the cube looks as expected seemed to flip uunpredictably, coming closer to the user for the front, right, top and bottom, and further back when showing back and left. It seem to take the shortest path and not rest on a single set of axis. Any help would be much appreciated.

Thanks!

            
                    <img class="cube__face cube__face--front smaller-image thin-img-border" src='./Image.jpeg' alt="Image">
            
                    <img class="cube__face cube__face--back smaller-image thin-img-border" src='./Image.jpg' alt="Image">
            
                    <img class="cube__face cube__face--right smaller-image thin-img-border" src='./Image.jpg' alt="Image">
            
                    <img class="cube__face cube__face--left smaller-image thin-img-border" src='./Image.jpeg' alt="Image">
            
                    <img class="cube__face cube__face--top smaller-image thin-img-border" src='./Image.jpg' alt="Image">
            
                    <img class="cube__face cube__face--bottom smaller-image thin-img-border" src='./Image.jpg' alt="Image">
            
        </div>

**Comment by desandro** [comment]
Sorry to hear you're having trouble. This article is a tutorial to help you get started. Sorry, but I am not able to provide personal support.
