### ISSUE TITLE
Error in explanation

### ISSUE THREAD

**Issue by marcusgsta** [desandro/3dtransforms#30]
On the page: https://3dtransforms.desandro.com/cube
the following sentence:

"Now all the faces are placed on top of one another, ready to be rotated. .cube__face--left and .cube__face--right will use rotateX() so they are rotated around the vertical X axis."

should be:

"Now all the faces are placed on top of one another, ready to be rotated. .cube__face--top and .cube__face--bottom will use rotateX() so they are rotated around the vertical X axis."

Right?

**Comment by desandro** [comment]
Thank you for catching this error! This has been fixed. Please email yo@metafizzy.co to get some stickers!
