### ISSUE TITLE
Error in example code

### ISSUE THREAD

**Issue by marcusgsta** [desandro/3dtransforms#31]
The example code for the box on the page:  https://3dtransforms.desandro.com/box

.box {
  width: 200px;
  height: 300px;
}

should be 

.box {
  width: 300px;
  height: 200px;
}
The code on codepen is right, but not in the example code.

**Comment by desandro** [comment]
Thank you for catching this error! This has been fixed. Please email yo@metafizzy.co to get some stickers!
