### ISSUE TITLE
Can't seem to have 2 card flips.

### ISSUE THREAD

**Issue by nigef** [desandro/3dtransforms#7]
When I try to create 2 card flips, the first flip works, but the second does not.

What can be done to enable 2 or more card flips on the same page?

Thanks very much

**Comment by desandro** [comment]
Any chance you can show us what you are working on? Possibly in [jsFiddle](http://jsfiddle.net) or [CodePen](http://codepen.io)

**Comment by nigef** [comment]
Thanks, and sorry for not including example before, here's a quick fiddle of the two card flips.

Besides making two cards, the only change I made was changing:
document.getElementById('flip').addEventListener( 'click', function()

to this (to get rid of the button):
document.getElementById('card').addEventListener( 'click', function()

http://jsfiddle.net/5Y9n7/

**Comment by desandro** [comment]
Great! thanks for putting that together. Here's how I would do it:

http://codepen.io/desandro/pen/LetkB

I changed the mark up to use `.card` as a class, since we have multiple. Then I'm just using jQuery to toggle `flipped` class when a card is clicked.

**Comment by nigef** [comment]
Nicely done. Like a boss.

:)

**Comment by nigef** [comment]
Just noticed that this doesn't work in firefox http://codepen.io/desandro/pen/LetkB 
hmmm...

**Comment by desandro** [comment]
Good catch! I was missing `event` in `$('.card').click( function( event ) {`
